// This file has been autogenerated from a class added in the UI designer.

using Foundation;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;

using UIKit;
using CoreFoundation;
using AudioToolbox;
using MessageUI;
using CoreGraphics;

namespace FrenchPhraseBook
{
	partial class Categories : UITableViewController
	{


		//dictionary of categories
		Dictionary<int, string> categoryDict = new Dictionary<int, string>{
			{0,"\ud83d\udc65 First Time Meeting"}, {1,"\ud83d\udc8b Dating"}, {2, "\ud83d\udde3 General Conversation"}, {3,"\ud83d\ude91 Emergency"}, {4,"\ud83d\udcb3 Company & Business"},
			{5,"\ud83c\udfdb Travel"}, {6,"\ud83d\ude8d Public Transport"}, {7,"\ud83c\udf54 Food"},{8,"\ud83c\udf7d Family & friends"}, {9,"\ud83d\udcda School & Education"},
			{10,"\ud83d\udd0c Technology"}, {11,"\ud83d\udc54 Work"}, {12,"\ud83c\udf3b Gardening & Landscaping"}, {13,"\ud83d\udcaf Math & Numbers"}, {14,"\ud83d\udc60 Shopping"}
		};

		public override void MotionEnded(UIEventSubtype motion, UIEvent evt)
		{
			if(evt.Type == UIEventType.Motion) {
				UIAlertController helpControl = UIAlertController.Create("Need Help?", "On this page you will learn over 500 French phrases. Simply choose a category and have fun", UIAlertControllerStyle.Alert);

				UIAlertAction confirmed = UIAlertAction.Create("Cool", UIAlertActionStyle.Default, (Action) =>
				{
					helpControl.Dispose();
				});

				helpControl.AddAction(confirmed);

				if(this.PresentedViewController == null) {
					SystemSound sound = new SystemSound(4095);
					sound.PlaySystemSound();
					this.PresentViewController(helpControl, true, null);
				}
				else if(this.PresentedViewController != null) {
					this.PresentedViewController.DismissViewController(true, () =>
					{
						this.PresentedViewController.Dispose();
						SystemSound sound = new SystemSound(4095);
						sound.PlaySystemSound();
						this.PresentViewController(helpControl, true, null);

					});
				}
			}
		}

		public string categoryID = "categories";

		public Categories(IntPtr handle) : base(handle)
		{
		}

		public Categories() { }

		public override void ViewDidLoad()
		{
			this.TableView.RowHeight = 70.0f;
			this.TableView.SeparatorColor = UIColor.Gray;

			if(UIDevice.CurrentDevice.UserInterfaceIdiom == UIUserInterfaceIdiom.Phone) {
				switch(UIApplication.SharedApplication.StatusBarOrientation) {
					case UIInterfaceOrientation.Portrait:
						
						break;
					case UIInterfaceOrientation.PortraitUpsideDown:
						
						break;
					case UIInterfaceOrientation.Unknown:
						
						break;
					default:
						
						break;
				}
			}
		}

		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			UITableViewCell categoryCell = tableView.DequeueReusableCell(this.categoryID);

			if (categoryCell == null)
			{
				categoryCell = new UITableViewCell(UITableViewCellStyle.Value1, this.categoryID);

			}

			categoryCell.TextLabel.Text = this.categoryDict[indexPath.Row];
			categoryCell.Accessory = UITableViewCellAccessory.DisclosureIndicator;
			return categoryCell;
		}

		public override nint RowsInSection(UITableView tableView, nint section)
		{
			return this.categoryDict.Count;
		}



		public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
		{
			switch (indexPath.Row)
			{
				case 0: //first time meeting category
					FirstTimeMeeting firstTimeController = this.Storyboard.InstantiateViewController("FirstTimeMeeting") as FirstTimeMeeting;
					this.NavigationController.PushViewController(firstTimeController, true);
					break;

				case 1: //dating category
					DatingController datingController = this.Storyboard.InstantiateViewController("DatingController") as DatingController;
					this.NavigationController.PushViewController(datingController, true);
					break;

				case 2: //category
					GeneralConversation generalController = this.Storyboard.InstantiateViewController("GeneralConversation") as GeneralConversation;
					this.NavigationController.PushViewController(generalController, true);
					break;

				case 3: //emergency category
					EmergencyController emergencyController = this.Storyboard.InstantiateViewController("EmergencyController") as EmergencyController;
					this.NavigationController.PushViewController(emergencyController, true);
					break;

				case 4: //company business category
					BusinessController companyController = this.Storyboard.InstantiateViewController("BusinessController") as BusinessController;
					this.NavigationController.PushViewController(companyController, true);
					break;

				case 5: //travel category
					TravelController travelController = this.Storyboard.InstantiateViewController("TravelController") as TravelController;
					this.NavigationController.PushViewController(travelController, true);
					break;

				case 6: //public transport category
					TransportController publicTransportController_2 = this.Storyboard.InstantiateViewController("TransportController") as TransportController;
					this.NavigationController.PushViewController(publicTransportController_2, true);
					break;

				case 7: //food category
					FoodController foodController = this.Storyboard.InstantiateViewController("FoodController") as FoodController;
					this.NavigationController.PushViewController(foodController, true);
					break;

				case 8: //family and friends category 
					FamilyController familyController = this.Storyboard.InstantiateViewController("FamilyController") as FamilyController;
					this.NavigationController.PushViewController(familyController, true);
					break;

				case 9: //school & education 
					SchoolController schoolController = this.Storyboard.InstantiateViewController("SchoolController") as SchoolController;
					this.NavigationController.PushViewController(schoolController, true);
					break;
				case 10: //Technology 
					TechnologyController technologyController = this.Storyboard.InstantiateViewController("TechnologyController") as TechnologyController;
					this.NavigationController.PushViewController(technologyController, true);
					break;
				case 11: //Work  
					WorkController workController = this.Storyboard.InstantiateViewController("WorkController") as WorkController;
					this.NavigationController.PushViewController(workController, true);
					break;
				case 12: //Gardening  
					GardeningController gardeningController = this.Storyboard.InstantiateViewController("GardeningController") as GardeningController;
					this.NavigationController.PushViewController(gardeningController, true);
					break;
				case 13: //Math controller  
					MathNumbersController mathController = this.Storyboard.InstantiateViewController("MathNumbersController") as MathNumbersController;
					this.NavigationController.PushViewController(mathController, true);
					break;
				case 14: //Shopping controller  
					ShoppingController shoppingController = this.Storyboard.InstantiateViewController("ShoppingController") as ShoppingController;
					this.NavigationController.PushViewController(shoppingController, true);
					break;
				default:
					break;
			}
			tableView.DeselectRow(indexPath, true);
		}

	}
}
